MkibaBI/MkibaBI/Controllers/AuditLogController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

using PagedList;
using TrackerEnabledDbContext.Common.Models;

using MkibaBI.DAO;

namespace MkibaBI.Controllers
{    //[CustomAuthorize(RolesConfigKey = "RolesConfigKey")]
     // [CustomAuthorize(UsersConfigKey = "UsersConfigKey")]
    [DAO.security.CustomAuthorize(Roles = "Admin")]
    public class AuditLogController : Controller
    {
        private SBoardContext db = new SBoardContext();
        // GET: AuditLog
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, string Date1String, string Date2String,
            int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.EmailSortParm = String.IsNullOrEmpty(sortOrder) ? "email" : "";
            var audit = from s in db.AuditLog
                select s;
            foreach(var p in audit)
            {
                string s = p.UserName;
            }
            if (searchString != null || (Date1String != null && Date2String != null))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
               audit = audit.Where(s =>
                 s.UserName.ToUpper().Contains(searchString.ToUpper())
                 ||
                 s.UserName.ToUpper().Contains(searchString.ToUpper()));
            }

            else if (!String.IsNullOrEmpty(Date1String) && !String.IsNullOrEmpty(Date2String))
            {
                DateTime date = Convert.ToDateTime(Date1String);
                DateTime date2 = Convert.ToDateTime(Date2String);
               audit = from s in db.AuditLog
                          
                             where date <= s.EventDateUTC && date2 >= s.EventDateUTC
                             select s;


            }
            switch (sortOrder)
            {
                case "name_desc":
                    audit = audit.OrderByDescending(s => s.UserName);
                    break;

                case "Date":
                    audit = audit.OrderBy(s => s.EventDateUTC);
                    break;
                case "date_desc":
                    audit = audit.OrderByDescending(s => s.EventDateUTC);
                    break;
                default:
                 audit = audit.OrderBy(s => s.AuditLogId);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View( audit.ToPagedList(pageNumber, pageSize));
        }

        // GET: AuditLog/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          AuditLog audit = await db.AuditLog.FindAsync(id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }


        // POST: AuditLog/Create
       


        // GET: AdminShares/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          AuditLog audit = await db.AuditLog.FindAsync(id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }

        // POST: AdminShares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AuditLog audit = await db.AuditLog.FindAsync(id);
            db.AuditLog.Remove(audit);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MkibaBI/MkibaBI/Views/AuditLog/Delete.cshtml
@model TrackerEnabledDbContext.Common.Models.AuditLog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin-left:30%;margin-right:15%;margin-bottom: 10%; background: white;" class="col-md-12">
        <div class="panel-heading" style="background-color:#008080">
           <h3 style="color:white">Delete</h3>
    </div>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Details</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AuditLogId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AuditLogId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EventDateUTC)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EventDateUTC)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EventType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EventType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TypeFullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TypeFullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RecordId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RecordId)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

MkibaBI/MkibaBI/Views/AuditLog/Details.cshtml
@model TrackerEnabledDbContext.Common.Models.AuditLog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="content">
    <div class="container">

        <!-- Page-Title -->
        <div class="row">

            <div class="col-md-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title"><b> Audit Log Details</b></h4>

                    <hr />
                    <h4>User:@User.Identity.Name</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.AuditLogId)
                        </dt>

                        <dd>
                            @Html.DisplayNameFor(model => model.AuditLogId)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.UserName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.UserName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.EventDateUTC)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EventDateUTC)
                        </dd>

                        <dt>
                            Local Time
                        </dt>

                        <dd>

                            @DateTime.Parse(Html.DisplayFor(model => model.EventDateUTC).ToString()).ToLocalTime().ToString()

                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.EventType)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EventType)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TypeFullName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TypeFullName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.RecordId)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.RecordId)
                        </dd>

                    </dl>
                </div>
                <p>

                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
                </p>
            </div>
        </div>
    </div>

MkibaBI/MkibaBI/Views/AuditLog/Index.cshtml
@model PagedList.IPagedList<TrackerEnabledDbContext.Common.Models.AuditLog>
@using PagedList.Mvc;
<link <a href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script type="text/javascript">
    function onSubmitClick() {
        $('#myForm input[name="DXScript"]').remove();
        $('#myForm input[name="DXCss"]').remove();

    }
</script>

<div class="content">
    <div class="container">

        <!-- Page-Title -->
        <div class="row">

            
          
                    <div class="col-lg-12">
                        <div class="card-box">
                            @using (Html.BeginForm("Index", "AuditLog", FormMethod.Get))
                            {
                                <div class="panel-heading" style="background-color:#008080">
                                    <h3 style="color:white">Search</h3>
                                </div>
                                <div class="form-horizontal">


                                    <div class="form-group">
                                        <div class="col-md-4">
                                            UserName: @Html.TextBox("SearchString", ViewBag.CurrentFilter as
                                 string)

                                        </div>
                                        <div class="col-md-4">
                                            <input type="submit" class="btn btn-warning" value="Search" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            Start Date : @Html.JQueryUI().Datepicker("Date1String").ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            End.. Date : @Html.JQueryUI().Datepicker("Date2String").ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)
                                        </div>
                                        <div class="col-md-4">

                                            <input type="submit" onclick="onSubmitClick();" class="btn btn-warning" value="Search" />
                                        </div>
                                    </div>


                                </div>



                            }
                        </div>
                    </div>

                            <div class="col-lg-12">
                                <div class="card-box">
                                    <div class="panel-heading" style="background-color:#008080">
                                        <h3 style="color:white">Audit Log </h3>
                                    </div>
                                    <table class="table table-striped">
                                        <tr>

                                            <th>
                                                AuditLogId
                                            </th>
                                            <th>
                                                @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                                            </th>
                                            <th>
                                                @Html.ActionLink("EventDateUTC", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })

                                            </th>
                                            <th>
                                                Event Date Local
                                            </th>
                                            <th>
                                                EventType
                                            </th>
                                            <th>
                                                TypeFullName
                                            </th>


                                        </tr>

                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AuditLogId)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.UserName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.EventDateUTC)
                                                </td>
                                                <td>

                                                    @DateTime.Parse(Html.DisplayFor(modelItem => item.EventDateUTC).ToString()).ToLocalTime().ToString()
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.EventType)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.TypeFullName)
                                                </td>


                                                <td>


                                                    <a style="color:black" href="@Url.Action("Details", new { id = item.AuditLogId })">
                                                        <i class="glyphicon glyphicon-file"></i>

                                                    </a>
                                                    |

                                                </td>
                                            </tr>
                                        }

                                    </table>

                                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
                                    @Model.PageCount
                                    @Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter =
ViewBag.CurrentFilter
}))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>